# Generated by Django 4.2.6 on 2023-10-27 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
    ]
