# Generated by Django 4.2.6 on 2023-10-27 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='readed_time',
        ),
    ]
