# Generated by Django 4.2.6 on 2023-10-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=3, upload_to=''),
            preserve_default=False,
        ),
    ]
